### ISSUE TITLE
disable the 'websocket' support if the browser doesn't support websockets

### ISSUE THREAD

**Issue by aaronmbr** [ndt-project/ndt#180]
We need to disable the websocket support if the browser doesn't support websockets, similar to how we disable java support if the browser doesn't hava java installed.

**Comment by aaronmbr** [comment]
It should be doing this now, though I don't have a good way of verifying that that's the case as all my browsers support websockets...

**Comment by skostuch** [comment]
I've tested it on IE9 and this didn't work. When seeing code I spotted that instead of checking if both websockets variables in window are undefined it was checking if both were present so this condition wasn't doing what it was supposed to do. I have committed proper fix for that and now on IE9 WebSocket button is disabled.
